### ISSUE TITLE
sql查询回来的消息记录都是加密的怎么整

### ISSUE THREAD

**Issue by ydslash2** [opentdp/wechat-rest#12]
{
    "Payload": {
        "BytesExtra": "CgQIEBAAGhcIARITd3hpZF9zOGlwZXFjdnZpM3kyMhrUAQgHEs8BPG1zZ3NvdXJjZT4KCTxiaXpmbGFnPjA8L2JpemZsYWc+Cgk8cHVhPjE8L3B1YT4KCTxzaWxlbmNlPjA8L3NpbGVuY2U+Cgk8bWVtYmVyY291bnQ+NjY8L21lbWJlcmNvdW50PgoJPHNpZ25hdHVyZT52MV9MU0JtaW96aTwvc2lnbmF0dXJlPgoJPHRtcF9ub2RlPgoJCTxwdWJsaXNoZXItaWQ+PC9wdWJsaXNoZXItaWQ+Cgk8L3RtcF9ub2RlPgo8L21zZ3NvdXJjZT4KGiQIAhIgMzJiZjRjY2NjODcyOTZjMzk2YTdjNTRmY2FmMmU1ZGM=",
        "BytesTrans": null,
        "CompressContent": null,
        "CreateTime": "MTcwNDg2OTUwOA==",
        "DisplayContent": null,
        "FlagEx": "MA==",
        "IsSender": "MA==",
        "MsgSequence": "ODU2MDQ3NjU3",
        "MsgServerSeq": "MQ==",
        "MsgSvrID": "MTc2ODU2NTc2MjY4NDMwOTgwMw==",
        "Reserved0": "MA==",
        "Reserved1": "Mg==",
        "Reserved2": null,
        "Reserved3": null,
        "Reserved4": null,
        "Reserved5": null,
        "Reserved6": null,
        "Sequence": "MTcwNDg2OTUwODAwMA==",
        "Status": "Mg==",
        "StatusEx": "MA==",
        "StrContent": "57uf5LiA55qE77yM5ZWG5a625LiN6IO95pON5L2c",
        "StrTalker": "NDU4NDI2ODcyMjJAY2hhdHJvb20=",
        "SubType": "MA==",
        "TalkerId": "Mw==",
        "Type": "MQ==",
        "localId": "MTAw"
    }
}

**Comment by rehiy** [comment]
你用的什么版本，新版本有些数据我解析过了

**Comment by ydslash2** [comment]
优秀，最新版本的是中文的了
