### ISSUE TITLE
/api/enable_receiver消息转发设置成功，但是发送消息给机器人 没有推送进来

### ISSUE THREAD

**Issue by xiaochaodada** [opentdp/wechat-rest#13]
/api/enable_receiver消息转发设置成功，但是发送消息给机器人 没有推送进来

**Comment by rehiy** [comment]
我测试是可以的，你看下窗口的日志，有没有 call 到这个url

**Comment by xiaochaodada** [comment]
> 我测试是可以的，你看下窗口的日志，有没有 call 到这个url

现在是收到消息 程序就闪退了。我用发送接口都能正常发送消息，好像接收消息有问题。

**Comment by rehiy** [comment]
看下版本，1小时前刚发布了一个版本修复这个问题

**Comment by xiaochaodada** [comment]
> 看下版本，1小时前刚发布了一个版本修复这个问题

正常了。还有问题：httpd address 我把host改成外网地址，启动就闪退。本地地址的话，外网端口没法访问，端口是开放的。

**Comment by rehiy** [comment]
改成 0.0.0.0
