### ISSUE TITLE
怎么只保留SDK 模块 关闭群管，WEB 机器人这些功能？

### ISSUE THREAD

**Issue by cshitian** [opentdp/wechat-rest#16]
怎么只保留微信接口模块  关闭群管，WEB ，机器人这些功能？

然后还有一个推送消息的URL参数 能放在config.yml 写死啊

**Comment by rehiy** [comment]
设置白名单
________________________________
发件人: Hou Si Yuan ***@***.***>
发送时间: 2024年2月4日 13:48
收件人: opentdp/wechat-rest ***@***.***>
抄送: Subscribed ***@***.***>
主题: [opentdp/wechat-rest] 怎么只保留SDK 模块 关闭群管，WEB 机器人这些功能？ (Issue #16)


怎么只保留微信接口模块 关闭群管，WEB ，机器人这些功能？

然后还有一个推送消息的URL参数 能放在config.yml 写死啊

―

**Comment by cshitian** [comment]
推送消息的URL参数 能放在config.yml 写死吧

**Comment by rehiy** [comment]
下个版本会添加
