### ISSUE TITLE
怎么今天突然出问题了。。

### ISSUE THREAD

**Issue by li5bo5** [opentdp/wechat-rest#17]
用的讯飞星火，/api、回复没问题，但是/ai 回复就错误
=== New Message ===
::Id:: 2388580155301414123
::Type:: 1
::Sender:: Li5Bo500
::Content::
/ai 你是谁
::Xml::
<msgsource>
        <bizflag>0</bizflag>
        <pua>1</pua>
        <alnode>
                <inlenlist>7</inlenlist>
        </alnode>
        <signature>V1_MEzJoqEY|v1_PhdJJqJT</signature>
        <tmp_node>
                <publisher-id></publisher-id>
        </tmp_node>
</msgsource>
=== End Message ===
dial tcp: lookup spark-api.xf-yun.com: i/o timeout
用Gemini回复也是这样。，
Post "https://googai.173371.xyz/v1/models/gemini-pro:streamGenerateContent?%24alt=json%3Benum-encoding%3Dint&key=这里是我的api": dial tcp: lookup googai.173371.xyz: no such host

**Comment by rehiy** [comment]
可能是谷歌代理挂了，可以换个看看&nbsp;

     若海              https://www.rehiy.com      


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年2月5日(星期一) 中午11:03
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [opentdp/wechat-rest] 怎么今天突然出问题了。。 (Issue #17)





 
用的讯飞星火，/api、回复没问题，但是/ai 回复就错误
 === New Message ===
 ::Id:: 2388580155301414123
 ::Type:: 1
 ::Sender:: Li5Bo500
 ::Content::
 /ai 你是谁
 ::Xml::
 
 0
 1
 
 7
 
 V1_MEzJoqEY|v1_PhdJJqJT
 <tmp_node&gt;
 
 </tmp_node&gt;
 
 === End Message ===
 dial tcp: lookup spark-api.xf-yun.com: i/o timeout
 用Gemini回复也是这样。，
 Post "https://googai.173371.xyz/v1/models/gemini-pro:streamGenerateContent?%24alt=json%3Benum-encoding%3Dint&amp;key=这里是我的api": dial tcp: lookup googai.173371.xyz: no such host

**Comment by li5bo5** [comment]
> 可能是谷歌代理挂了，可以换个看看&nbsp; 若海 https://www.rehiy.com &nbsp;


怎么换？？在哪里填写？

**Comment by rehiy** [comment]
配置文件里面有写说明
