### ISSUE TITLE
win7下无法运行

### ISSUE THREAD

**Issue by moeik** [opentdp/wechat-rest#19]
点击直接闪退

**Comment by rehiy** [comment]
新版 golang 编译器不支持win7了
&nbsp;

     若海              https://www.rehiy.com      


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年2月18日(星期天) 下午2:58
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [opentdp/wechat-rest] win7下无法运行 (Issue #19)





 
点击直接闪退
