### ISSUE TITLE
公网ip时打开7600端口 会暴露信息

### ISSUE THREAD

**Issue by cshitian** [opentdp/wechat-rest#4]
能不能做一个关闭或隐藏的开关。

**Comment by rehiy** [comment]
默认监听的 127.0.0.1 不会暴露到公网，可以参考配置文件中的信息

**Comment by cshitian** [comment]
> 默认监听的 127.0.0.1 不会暴露到公网，可以参考配置文件中的信息

这个知道，但是如果想外网调用的话  就不行了

**Comment by rehiy** [comment]
在配置中添加一个token即可
```
    token: "" # 使用 token 验证请求
```

**Comment by cshitian** [comment]
> 在配置中添加一个token即可
> 
> ```
>     token: "" # 使用 token 验证请求
> ```

咳咳  其实就是不想被爬虫抓取 然后公布到搜索结果上去了

**Comment by rehiy** [comment]
你是想禁止显示api文档页面？

**Comment by rehiy** [comment]
若设置了 token，请求时需携带 header 信息: Authorization: v1 $token

**Comment by cshitian** [comment]
> 你是想禁止显示api文档页面？

是的 是的

**Comment by rehiy** [comment]
明白了，下个版本我正好要调整文档的路径，一起调整下这里的参数
