### ISSUE TITLE
 token: "" # 使用 token 验证请求     这个是怎么带入请求里？

### ISSUE THREAD

**Issue by cshitian** [opentdp/wechat-rest#5]
curl -X 'GET' \
  'http://127.0.0.1:7600/api/self_wxid' \
  -H 'accept: application/json'
  -H 'token: 123456789' \

好像不行
{
	"Error": {
		"Code": 401,
		"Message": "未授权的操作"
	}
}

**Comment by rehiy** [comment]
若设置了 token，请求时需携带 header 信息: Authorization: v1 $token
