### ISSUE TITLE
开启转发消息和关闭转发消息好像有一个BUG

### ISSUE THREAD

**Issue by cshitian** [opentdp/wechat-rest#6]
1.开启转发消息发送url:a.php，如果去关闭转发消息的话，比如url是b.php,那么a.php会失效。
2.如果重新再开启转发消息发送url:a.php，会提示url already exists，得重新启动程序才能true。

：感觉关闭转发消息不管你发送什么地址，它都会关闭所有的。然后重新开启的话，不能重复开启，你得换一个地址(而且上上次的地址也不能)。

**Comment by rehiy** [comment]
这里的确有个bug，关闭时未清空列表

**Comment by rehiy** [comment]
fixed
