### ISSUE TITLE
打开报错应该如何使用？

### ISSUE THREAD

**Issue by pcstx** [opentdp/wechat-rest#8]
默认配置直接打开日志里面提示：level=WARN msg="call dll:WxInitSDK" r1=0 r2=0 error="Attempt to access invalid address."
然后访问网址127.0.0.1:7600查看接口，报错 {"Error":{"Message":"内部错误"}} 

发送消息给微信，开启消息日志后是可以看到接收消息的日志的。
应该如何使用？

**Comment by rehiy** [comment]
是否设置了 token ？

**Comment by pcstx** [comment]
直接访问 http://127.0.0.1:7600/swag 报错500。要改成 http://127.0.0.1:7600/swag/  go的路由配置应该需要兼容下

**Comment by rehiy** [comment]
收到，下个版本我兼容下
